/* SIDeN UI enhancements v1.4 */
(function(){
  'use strict';
  const getConfig=async()=>{
    if(window.__SIDEN_CONFIG__&&window.__SIDEN_CONFIG__.siden) return window.__SIDEN_CONFIG__;
    try{const r=await fetch('config.json',{cache:'no-cache'});return r.ok?await r.json():null}catch(e){return null}
  };
  const asset=(cfg,file)=>{const prefix=String(cfg?.siden?.assetPrefix||'').replace(/\/+$/,'');return new URL((prefix?prefix+'/':'/')+String(file||'').replace(/^\/+/,''),location.origin).href};
  const openLightbox=(src,alt)=>{let box=document.querySelector('.siden-lightbox');if(!box){box=document.createElement('div');box.className='siden-lightbox';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');box.innerHTML='<button type="button" aria-label="Cerrar">×</button><img alt="">';document.body.appendChild(box);box.addEventListener('click',e=>{if(e.target===box||e.target.tagName==='BUTTON'||e.target===box.querySelector('img'))box.classList.remove('active')});document.addEventListener('keydown',e=>{if(e.key==='Escape')box.classList.remove('active')})}const img=box.querySelector('img');img.src=src;img.alt=alt||'';box.classList.add('active')};
  const setupMenu=()=>{const btn=document.getElementById('menu-button'),links=document.getElementById('nav-links');if(!btn||!links||btn.dataset.sidenBound==='1')return;btn.dataset.sidenBound='1';btn.addEventListener('click',()=>{const active=links.classList.toggle('active');btn.setAttribute('aria-expanded',String(active));btn.textContent=active?'×':'☰'});links.addEventListener('click',e=>{if(e.target.closest('a')){links.classList.remove('active');btn.setAttribute('aria-expanded','false');btn.textContent='☰'}})};
  const setupMedia=async()=>{const cfg=await getConfig();if(!cfg)return;const services=document.getElementById('lista-servicios');if(services&&Array.isArray(cfg.servicios)){services.innerHTML='';cfg.servicios.forEach(s=>{const card=document.createElement('article');card.className='service';if(s.imagen){const img=document.createElement('img');img.className='service-image';img.src=asset(cfg,'images/'+s.imagen);img.alt=(s.nombre||'Servicio')+' - '+(cfg.nombre||'');img.loading='lazy';card.appendChild(img)}const content=document.createElement('div');content.className='service-content';const h=document.createElement('h3');h.textContent=s.nombre||'';const p=document.createElement('p');p.textContent=s.descripcion||'';content.append(h,p);card.appendChild(content);services.appendChild(card)})}document.querySelectorAll('#lista-servicios img.service-image,#lista-productos .product img,.gallery img,#lista-menu .menu-item img').forEach(img=>{if(img.dataset.sidenLightbox==='1')return;img.dataset.sidenLightbox='1';img.addEventListener('click',()=>openLightbox(img.src,img.alt))})};
  const start=()=>{setupMenu();window.addEventListener('load',()=>setTimeout(setupMedia,150),{once:true});setTimeout(setupMedia,900)};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
